export const MAP_SKINS = [
  {
    id: 'forest',
    name: 'Floresta',
    accent: '#76e4a8',
    skyTop: '#0f1f22',
    skyBottom: '#173d36',
    obstacle: '#7af0af',
    glow: 'rgba(122, 240, 175, 0.35)',
    detail: '#d8ffe9',
    unlockType: 'default',
    unlockValue: 0,
    description: 'Brisa verde com brilho orgânico.',
  },
  {
    id: 'desert',
    name: 'Deserto',
    accent: '#ffbf69',
    skyTop: '#28140e',
    skyBottom: '#5c3018',
    obstacle: '#ffce84',
    glow: 'rgba(255, 191, 105, 0.35)',
    detail: '#fff0d0',
    unlockType: 'score',
    unlockValue: 12,
    description: 'Cores quentes e dunas ao fundo.',
  },
  {
    id: 'snow',
    name: 'Neve',
    accent: '#8fd8ff',
    skyTop: '#11213a',
    skyBottom: '#1a4f7a',
    obstacle: '#a9e7ff',
    glow: 'rgba(143, 216, 255, 0.35)',
    detail: '#effcff',
    unlockType: 'coins',
    unlockValue: 260,
    description: 'Ambiente cristalino com brilho gelado.',
  },
  {
    id: 'future',
    name: 'Futurista',
    accent: '#ffd84d',
    skyTop: '#090a14',
    skyBottom: '#1d1f40',
    obstacle: '#ffe476',
    glow: 'rgba(255, 216, 77, 0.35)',
    detail: '#fff6b6',
    unlockType: 'score',
    unlockValue: 24,
    description: 'Neon limpo com skyline arcade.',
  },
]

export const SHOP_PACKS = [
  {
    id: 'revive_pack',
    title: 'Kit Continue',
    description: '+3 continues instantaneos',
    priceCoins: 180,
    kind: 'revive',
    amount: 3,
  },
  {
    id: 'coin_boost',
    title: 'Booster de Moedas',
    description: '+220 moedas para skins',
    priceCoins: 0,
    kind: 'coins',
    amount: 220,
    rewardOnly: true,
  },
]

export const STORE_PRODUCTS = [
  {
    id: 'remove_ads',
    title: 'Remover Anuncios',
    description: 'Compra unica com dinheiro real',
    displayPrice: 'R$ 14,90',
  },
  {
    id: 'coin_pack_small',
    title: 'Pacote 500 moedas',
    description: 'Compra em dinheiro real para acelerar skins',
    displayPrice: 'R$ 9,90',
  },
  {
    id: 'revive_pack_iap',
    title: 'Pacote 5 continues',
    description: 'Compra em dinheiro real para runs longas',
    displayPrice: 'R$ 6,90',
  },
]
